import Mailgen from "mailgen";
import nodemailer from "nodemailer";
import dotenv from "dotenv";
dotenv.config();

/**
 * sendMail - Sends an email using Mailgen + Nodemailer
 * @param {Object} options - Contains email, subject, and mailgenContent
 */
const sendMail = async (options) => {
  // 1️⃣ Initialize Mailgen with theme and product info (appears in footer)
  const mailGenerator = new Mailgen({
    theme: "default",
    product: {
      name: "Blog App by Khushboo",
      link: "https://blog/app", // shown as footer link
    },
  });

  // 2️⃣ Generate plain text and HTML versions of the email from mailgen content
  const emailText = mailGenerator.generatePlaintext(options.mailgenContent);
  const emailHtml = mailGenerator.generate(options.mailgenContent);

  // 3️⃣ Create a nodemailer transporter (SMTP configuration)
  const transporter = nodemailer.createTransport({
    host: process.env.EMAIL_HOST,
    port: Number(process.env.EMAIL_PORT),
    secure: process.env.EMAIL_PORT == 465, // use secure true only for port 465
    auth: {
      user: process.env.EMAIL_USER,
      pass: process.env.EMAIL_PASS,
    },
  });

  // 4️⃣ Construct the actual mail to be sent
  const mail = {
    from: process.env.EMAIL_USER,
    to: options.email, // recipient
    subject: options.subject, // email subject
    text: emailText, // fallback for clients that don’t render HTML
    html: emailHtml, // pretty HTML version generated by Mailgen
  };

  // 5️⃣ Send the email and handle any errors
  try {
    await transporter.sendMail(mail);
    console.log(`✅ Email sent successfully to ${options.email}`);
  } catch (error) {
    console.error(
      "❌ Email service failed. Make sure .env credentials are correct."
    );
    console.error("Error:", error);
  }
};

// generate the mail
const emailVerificationContent = (userName, verificationurl) => {
  return {
    body: {
      name: userName,
      intro: "welcome to our app we are exicted to have you on board",
      action: {
        instructions: "To veriy you email please click on the button ",
        button: {
          color: "#1aae",
          text: "verify your email",
          link: verificationurl,
        },
      },
      outro:
        "Need help or any question , just reply to this email we would love to help you ",
    },
  };
};

const forgetPasswordMailgenContent = (userName, passwordResetUrl) => {
  return {
    body: {
      name: userName,
      intro: "we got request to reset your password",
      action: {
        instructions: "To reset your passwrod click on the following button ",
        button: {
          color: "#1aae",
          text: "Reset passwrod",
          link: passwordResetUrl,
        },
      },
      outro:
        "Need help or any question , just reply to this email we would love to help you ",
    },
  };
};

export { forgetPasswordMailgenContent, emailVerificationContent, sendMail };
